version: '3.3'
services:
  tests:
    build:
      context: ${PWD}
      dockerfile: ${PWD}/infra/docker/tests.dockerfile
    command: bash -c "while true; do sleep 1; done"
    env_file:
      - ${PWD}/.env/api.test.env
      - ${PWD}/.env/db.test.env
    environment:
      - SERVER_NAME=localhost:8080
  api:
    build:
      context: ${PWD}
      dockerfile: ${PWD}/infra/docker/api.local.dockerfile
    env_file:
       - ${PWD}/.env/api.test.env
       - ${PWD}/.env/db.test.env
  api:
    
