version: "3.3"
services:
  bountydns:
    volumes:
      - ./../../bountydns:/bountydns/bountydns
      - ./../../bdnsctl.py:/bountydns/bdnsctl.py
      - ./../../requirements.txt:/bountydns/requirements.tx
  dns:
    volumes:
      - ./../../bountydns:/bountydns/bountydns
      - ./../../bdnsctl.py:/bountydns/bdnsctl.py
      - ./../../requirements.txt:/bountydns/requirements.tx
  http:
    volumes:
      - ./../../bountydns:/bountydns/bountydns
      - ./../../bdnsctl.py:/bountydns/bdnsctl.py
      - ./../../requirements.txt:/bountydns/requirements.tx
  proxy:
    volumes:
      - ./../../webui/dist:/var/www/app/webui
      - ./../../landing:/var/www/app/landing
